<?php

define('FIREBALL_NEWS_COMMENTS', 1);
define('FIREBALL_NEWS_VIEW', 'article');
define('FIREBALL_NEWS_MESSAGE_SIDEBAR', 1);
define('FIREBALL_NEWS_MESSAGE_MAXLENGTH', 10000);
define('FIREBALL_NEWS_NEWS_IMAGES_ATTACHED', 1);
define('FIREBALL_NEWS_NEWS_IMAGES_FULLSCREEN', 0);
define('FIREBALL_NEWS_SIDEBAR_CATEGORIES', 1);
define('FIREBALL_NEWS_SIDEBAR_CATEGORIES_MAIN', 0);
define('FIREBALL_NEWS_SIDEBAR_SEARCH', 0);
define('FIREBALL_NEWS_LANGUAGEICON', 1);
define('FIREBALL_NEWS_PER_PAGE', 10);
define('FIREBALL_NEWS_TRUNCATE_PREVIEW', 500);
define('FIREBALL_NEWS_LATEST_LIMIT', 10);
define('FIREBALL_NEWS_SIGNATURES', 1);
define('FIREBALL_NEWS_DISCLAIMER', '');
define('FIREBALL_NEWS_DISCLAIMER_GUESTS', 0);
define('FIREBALL_NEWS_DISCLAIMER_USERS', 0);
