ALTER TABLE cms1_news ADD COLUMN deletedByID     INT(10);
ALTER TABLE cms1_news ADD COLUMN deletedBy       VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms1_news ADD COLUMN deleteReason    INT(10)      NOT NULL DEFAULT 0;
ALTER TABLE cms1_news ADD COLUMN isDelayed       TINYINT(1)   NOT NULL DEFAULT 0;
ALTER TABLE cms1_news ADD COLUMN hasLabels       TINYINT(1)   NOT NULL DEFAULT 0;
ALTER TABLE cms1_news ADD FOREIGN KEY (deletedByID) REFERENCES wcf1_user (userID) ON DELETE SET NULL;
